import "./globals.css";
import Footer from "@/components/layout/Footer";
import Navibar from "@/components/layout/Navibar";
import { AuthProvider } from "@/context/authContext";

export const metadata = {
  title: "Healthcon",
  description: "Generated by create next app",
  icons: "./logo.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth" className="h-full antialiased">
      <body className="min-h-screen flex flex-col scroll-smooth">
        <AuthProvider>
          <Navibar style="bg-healthcon-blue"/>
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
